export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE'
export const LOAD_PROFILE_REQUEST = 'LOAD_PROFILE_REQUEST'
